FROM node:22-alpine

WORKDIR /app

# Garante compatibilidade para bibliotecas nativas que esperam glibc
RUN apk add --no-cache libc6-compat

COPY package*.json ./
# Evita erros de peer deps no Docker.
RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 4200
# -- separa argumentos do NPM e argumentos do Angular
# --host=0.0.0.0 faz o Angular servir para fora do container
CMD ["npm", "run", "start", "--", "--host=0.0.0.0"]
