FROM node:22-alpine

WORKDIR /app

# Dependências do sistema (openssl é importante para o Prisma)
RUN apk add --no-cache openssl

COPY package*.json ./
RUN npm install

RUN npm install -g @nestjs/cli

COPY . .

# Gera o Prisma Client
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]